apiVersion: v1
kind: Service
metadata:
  name: fla-service-a-internal-ingress
  namespace: fla-na-a
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  #loadBalancerIP: 10.128.0.54
  externalTrafficPolicy: Cluster
  selector:
    app: fla-response-a
  ports:
  - name: tcp-port
    protocol: TCP
    port: 8080
    targetPort: 8080
