apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: fla-deployment-a
  namespace: default-a
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fla-deployment-a
  updatePolicy:
    updateMode: "Off"  # Auto | Initial | Off