apiVersion: apps/v1
kind: Deployment
metadata:
  name: fla-deployment-z
  namespace: default-z
  labels:
    app: fla-response-z
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fla-response-z
  template:
    metadata:
      labels:
        app: fla-response-z
    spec:
      #nodeSelector:
        #cloud.google.com/gke-nodepool: nodepool-apps
        #process: medium
      containers:
      - env:
        - name: PORT
          value: '8080'
        - name: UDP_PORT
          value: '5005'
        - name: PROXY_HTTP_PORT
          value: '9191'
        - name: PROXY_TCP_PORT
          value: '9090'
        - name: WEBSOCKET_PORT
          value: '5678'
        - name: GRPC_PORT
          value: '50051'
        - name: WORKERS
          value: '1'  # this increase ram required
        - name: TIMEOUT
          value: '120'
        - name: VERSION_DEP
          value: 'vp.0.0.1a'
        - name: INIT_APP_TIME
          value: '0'
        - name: SLEEP_TIME
          value: '0'
        - name: LETS_TOKEN
          value: ''
        - name: LOGS_PRINT
          value: 'false'
        - name: CERTFILE_CRT
          value: '.certs/tls.crt'  # absolute or relative path for certs .certs/tls.crt 
        - name: KEYFILE_TLS
          value: '.certs/tls.key'  # absolute or relative path for certs .certs/tls.key 
        - name: CHAIN_PEM
          value: '.certs/chain.pem'  # absolute or relative path for client certs .certs/chain.pem
        image: poxstone/flask_any_response
        #imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 30
          #tcpSocket:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
          #exec:
          #  command:
          #  - sleep
          #  - 10
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 60
        name: fla-response-z
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
        - containerPort: 5005
        - containerPort: 5678
        - containerPort: 9191
        - containerPort: 9090
        - containerPort: 50051
        readinessProbe:
          failureThreshold: 30
          #tcpSocket:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
          #exec:
          #  command:
          #  - sleep
          #  - 10
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 60
        resources:
          #limits:
          #  cpu: 500m
          #  memory: 256Mi
          requests:
            cpu: 20m
            memory: 118Mi
        volumeMounts:
        #- mountPath: /app/.certs-self/
        #  name: tls-domain
      ## mout for minikube
      volumes:
      #- name: tls-domain  #  minikube mount
      #  hostPath: 
      #    path: /mount
      #- name: tls-domain  # normal k8s secret
      #  secret:
      #    secretName: fla-secret-service-a
