apiVersion: apps/v1
kind: Deployment
metadata:
  name: fla-deployment-a
  namespace: fla-na-a
  labels:
    app: fla-app-a  # may not required for group app
    deploy: fla-deployment-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fla-app-a  # required for group app
      pod: fla-pod-a
      version: fla-v1
  template:
    metadata:
      labels:
        app: fla-app-a  # required for group app
        pod: fla-pod-a
        version: fla-v1
    spec:
      serviceAccountName: fla-serviceaccount-a
      nodeSelector:
        #cloud.google.com/gke-nodepool: nodepool-apps
        #process: medium
      containers:
      - name: fla-container
        image: poxstone/flask_any_response
        imagePullPolicy: IfNotPresent  # IfNotPresent Always Never
        env:
        - name: PORT
          value: '8080'
        - name: NGINX_PORT
          value: '80'  # 443 for https and http2
        - name: UDP_PORT
          value: '5005'
        - name: PROXY_HTTP_PORT
          value: '9191'
        - name: PROXY_TCP_PORT
          value: '9090'
        - name: WEBSOCKET_PORT
          value: '5678'
        - name: GRPC_PORT
          value: '50051'
        - name: WORKERS
          value: '2'  # this increase ram required
        - name: TIMEOUT
          value: '180'
        - name: VERSION_DEP
          value: 'vp.0.0.1a'
        - name: INIT_APP_TIME
          value: '0'
        - name: SLEEP_TIME
          value: '0'
        - name: COOKIE_VAL
          value: 'fla-key1,fla-value1,3600,,,,True,False,None'
        - name: LOGS_PRINT
          value: 'false'
        - name: CERTFILE_CRT
          value: '.certs-self/tls.crt'  # absolute or relative path for certs .certs/tls.crt 
        - name: KEYFILE_TLS
          value: '.certs-self/tls.key'  # absolute or relative path for certs .certs/tls.key 
        - name: CHAIN_PEM
          value: '.certs-self/chain.pem'  # absolute or relative path for client certs .certs/chain.pem
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
        - containerPort: 5005
        - containerPort: 5678
        - containerPort: 9191
        - containerPort: 9090
        - containerPort: 50051
        # comment for gcp ingress initial
        #readinessProbe:
        #  initialDelaySeconds: 15  #5-15 (45)
        #  periodSeconds: 15  #5-15 (15)
        #  timeoutSeconds: 5  #1-5 (60)
        #  successThreshold: 1  #1-3 (1)
        #  failureThreshold: 5  #no especified (4)
        #  #tcpSocket:
        #  httpGet:
        #    path: /index.html
        #    port: 8080
        #    scheme: HTTP  # HTTPS TCP
          #exec:
          #  command:
          #  - "sleep"
          #  - "10"
        #livenessProbe:
        #  initialDelaySeconds: 30  #10-30 (50)
        #  periodSeconds: 15  #5-15 (15)
        #  timeoutSeconds: 5  #1-5 (60)
        #  successThreshold: 1  #3-5 (1)
        #  failureThreshold: 5  #3-5 (30)
        #  #tcpSocket:
        #  httpGet:
        #    path: /index.html
        #    port: 8080
        #    scheme: HTTP  # HTTPS TCP
          #exec:
          #  command:
          #  - "sleep"
          #  - "3"
        resources:
          limits:
            cpu: 160m  #100m default; 1worker=25-375 2w=27-388
            memory: 180Mi
          requests:
            cpu: 140m  # 50m normal, 14m for test stress 1w
            memory: 160Mi  # 1worker=120-130 2w=140-150
        volumeMounts:
        #- mountPath: /app/.certs/
        #  name: tls-domain
        #- mountPath: /app/.certs-self/
        #  name: tls-service
      volumes:
      #- name: tls-domain  #  minikube mount
      #  hostPath: 
      #    path: /mount
      #- name: tls-domain  # normal k8s secret
      #  secret:
      #    secretName: secret-main-domain-tls
      #- name: tls-service  # normal k8s secret
      #  secret:
      #    secretName: fla-secret-service-a
