apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: default
spec:
  selector:
    app: service-a
  ports:
    - name: http
      protocol: TCP
      port: 8080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: default
spec:
  selector:
    app: service-b
  ports:
    - name: http
      protocol: TCP
      port: 8080
  type: NodePort
