apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-any-response-a
  name: flask-any-deployment-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-any-response-a
  strategy: {}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: flask-any-response-a
        kubectl.kubernetes.io/default-logs-container: flask-any-response-a
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/status: '{"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}'
      creationTimestamp: null
      labels:
        app: flask-any-response-a
        security.istio.io/tlsMode: istio
        service.istio.io/canonical-name: flask-any-response-a
        service.istio.io/canonical-revision: latest
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: UDP_PORT
          value: "5005"
        - name: PROXY_HTTP_PORT
          value: "9191"
        - name: PROXY_TCP_PORT
          value: "9090"
        - name: WEBSOCKET_PORT
          value: "5678"
        - name: WORKERS
          value: "3"
        - name: TIMEOUT
          value: "120"
        - name: VERSION_DEP
          value: vp.0.0.1a
        - name: INIT_APP_TIME
          value: "0"
        - name: LOGS_PRINT
          value: 'true'
        image: poxstone/flask_any_response:latest
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /app-health/flask-any-response-a/livez
            port: 15020
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        name: flask-any-response-a
        ports:
        - containerPort: 8080
        - containerPort: 5005
        - containerPort: 5678
        - containerPort: 9191
        - containerPort: 9090
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /app-health/flask-any-response-a/readyz
            port: 15020
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
      - args:
        - proxy
        - sidecar
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --log_output_level=default:info
        - --concurrency
        - "2"
        env:
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: istiod.istio-system.svc:15012
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: PROXY_CONFIG
          value: |
            {}
        - name: ISTIO_META_POD_PORTS
          value: |-
            [
                {"containerPort":8080}
                ,{"containerPort":5005}
                ,{"containerPort":5678}
                ,{"containerPort":9191}
                ,{"containerPort":9090}
            ]
        - name: ISTIO_META_APP_CONTAINERS
          value: flask-any-response-a
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_META_MESH_ID
          value: cluster.local
        - name: TRUST_DOMAIN
          value: cluster.local
        - name: ISTIO_KUBE_APP_PROBERS
          value: '{"/app-health/flask-any-response-a/livez":{"httpGet":{"path":"/index.html","port":8080,"scheme":"HTTP"},"timeoutSeconds":3},"/app-health/flask-any-response-a/readyz":{"httpGet":{"path":"/index.html","port":8080,"scheme":"HTTP"},"timeoutSeconds":3}}'
        image: docker.io/istio/proxyv2:1.13.3
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15021
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/lib/istio/data
          name: istio-data
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /var/run/secrets/tokens
          name: istio-token
        - mountPath: /etc/istio/pod
          name: istio-podinfo
      initContainers:
      - args:
        - istio-iptables
        - -p
        - "15001"
        - -z
        - "15006"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - '*'
        - -d
        - 15090,15021,15020
        image: docker.io/istio/proxyv2:1.13.3
        name: istio-init
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - emptyDir: {}
        name: istio-data
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              fieldPath: metadata.annotations
            path: annotations
        name: istio-podinfo
      - name: istio-token
        projected:
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
      - configMap:
          name: istio-ca-root-cert
        name: istiod-ca-cert
status: {}
---
