
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fla-cronjob-a-1
  namespace: default-a
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Allow  # Allow | Forbid | Replace
  #ttlSecondsAfterFinished: 120
  jobTemplate:
    spec:
      template:
        spec:
          #nodeSelector:
          #  cloud.google.com/gke-nodepool: nodepool-apps
          #  process: bigExtraPapa
          containers:
          - name: fla-cronjob-response-a
            image: poxstone/flask_any_response
            command: ["stress-ng",  "--cpu", "1", "-t", "3m", "--vm-bytes", "128M"]
            env:
            - name: ENTRYPOINT
              value: 'stress-ng --cpu 1 -t 3m --vm-bytes 128M'
          restartPolicy: OnFailure
      backoffLimit: 4
