
apiVersion: batch/v1
kind: Job
metadata:
  name: fla-job-a-1
  namespace: fla-na-a
spec:
  template:
    spec:
      #nodeSelector:
      #  cloud.google.com/gke-nodepool: nodepool-apps
      #  process: bigExtraPapa
      containers:
      - name: fla-job-response-a
        image: poxstone/flask_any_response
        command: ["stress-ng",  "--cpu", "1", "-t", "3m", "--vm-bytes", "128M"]
        env:
          - name: ENTRYPOINT
            value: 'stress-ng --cpu 1 -t 3m --vm-bytes 128M'
      restartPolicy: Never
  backoffLimit: 4