# https://istio.io/latest/docs/reference/config/security/conditions/
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: fla-authorizationpolicy-a
  namespace: default-a
spec:
  action: DENY  # DENY CUSTOM ALLOW  
  rules:
  - from:
    - source:
        principals: ["sa-service-z"]  # not works
        #namespaces: ["default-z"]
        #notIpBlocks: ["10.244.0.17"]
    to:
    - operation:
        hosts: ["service-b.default-a.svc.cluster.local","service-b"]
        ports: ["80"]
    #when:
    #  - key: "source.principal"
    #    values: ["cluster.local/ns/default-z/sa/sa-service-z"]
    #  #- key: "remote.ip"
    #  #  values: ["10.244.0.15"]
