apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-any-deployment-a
  namespace: default
  labels:
    app: flask-any-response-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-any-response-a
  template:
    metadata:
      labels:
        app: flask-any-response-a
    spec:
      nodeSelector:
        #cloud.google.com/gke-nodepool: nodepool-apps
        #process: medium
      containers:
      - name: flask-any-response-a
        env:
        - name: PORT
          value: '8080'
        - name: UDP_PORT
          value: '5005'
        - name: PROXY_HTTP_PORT
          value: '9191'
        - name: PROXY_TCP_PORT
          value: '9090'
        - name: WEBSOCKET_PORT
          value: '5678'
        - name: GRPC_PORT
          value: '50051'
        - name: WORKERS
          value: '3'  # this increase ram required
        - name: TIMEOUT
          value: '120'
        - name: VERSION_DEP
          value: 'vp.0.0.1a'
        - name: INIT_APP_TIME
          value: '0'
        - name: SLEEP_TIME
          value: '0'
        - name: LETS_TOKEN
          value: ''
        - name: LOGS_PRINT
          value: 'false'
        - name: CERTFILE_CRT
          value: '.certs/tls.crt'  # absolute or relative path for certs .certs/tls.crt 
        - name: KEYFILE_TLS
          value: '.certs/tls.key'  # absolute or relative path for certs .certs/tls.key 
        - name: CA_CERT_TLS
          value: '.certs/chain.pem'  # absolute or relative path for client certs .certs/chain.pem
        image: poxstone/flask_any_response
        #imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 2
          #tcpSocket:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP  # HTTPS TCP
          #exec:
          #  command:
          #  - "sleep"
          #  - "3"
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 2
          #tcpSocket:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP  # HTTPS TCP
          #exec:
          #  command:
          #  - "sleep"
          #  - "10"
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
        - containerPort: 5005
        - containerPort: 5678
        - containerPort: 9191
        - containerPort: 9090
        - containerPort: 50051
        resources:
          limits:
          #  cpu: 500m
          #  memory: 256Mi
          requests:
            cpu: 200m
            memory: 96Mi
        volumeMounts:
        #- mountPath: /app/.certs/
        #  name: tls-domain
      ## mout for minikube
      volumes:
      #- name: tls-domain  #  minikube mount
      #  hostPath: 
      #    path: /mount
      - name: tls-domain  # normal k8s secret
      #  secret:
      #    secretName: secret-flask-tls
