apiVersion: v1
kind: Service
metadata:
  name: fla-service-c
  namespace: fla-na-c
  labels:
    app: fla-app-c  # required for group app
spec:
  selector:
    pod: fla-pod-c
    version: fla-v1
  ports:
    - name: http-web
      protocol: TCP  # "SCTP", "TCP", "UDP"
      port: 8080  # 8080 443
      targetPort: 8080
    - name: http-nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-proxy
      protocol: TCP
      port: 9191
      targetPort: 9191
    - name: http-proxy-tcp
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: http-udp
      protocol: UDP
      port: 5005
      targetPort: 5005
    - name: http-ws
      protocol: TCP
      port: 5678
      targetPort: 5678
    - name: grpc-http
      protocol: TCP
      port: 50051
      targetPort: 50051
  #type: LoadBalancer  # for tcp lb
  type: ClusterIP  # for ingress, gateway
  #type: NodePort  # gateway

---
apiVersion: v1
kind: Service
metadata:
  name: fla-service-d
  namespace: fla-na-c
  labels:
    app: fla-app-d  # required for group app
spec:
  selector:
    pod: fla-pod-d
    version: fla-v1
  ports:
    - name: http-web
      protocol: TCP  # "SCTP", "TCP", "UDP"
      port: 8080  # 8080 443
      targetPort: 8080
    - name: http-nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-proxy
      protocol: TCP
      port: 9191
      targetPort: 9191
    - name: http-proxy-tcp
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: http-udp
      protocol: UDP
      port: 5005
      targetPort: 5005
    - name: http-ws
      protocol: TCP
      port: 5678
      targetPort: 5678
    - name: grpc-http
      protocol: TCP
      port: 50051
      targetPort: 50051
  #type: LoadBalancer  # for tcp lb
  type: ClusterIP  # for ingress, gateway
  #type: NodePort  # gateway

---
apiVersion: v1
kind: Service
metadata:
  name: fla-service-e
  namespace: fla-na-c
  labels:
    app: fla-app-e  # required for group app
spec:
  selector:
    pod: fla-pod-e
    version: fla-v1
  ports:
    - name: http-web
      protocol: TCP  # "SCTP", "TCP", "UDP"
      port: 8080  # 8080 443
      targetPort: 8080
    - name: http-nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-proxy
      protocol: TCP
      port: 9191
      targetPort: 9191
    - name: http-proxy-tcp
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: http-udp
      protocol: UDP
      port: 5005
      targetPort: 5005
    - name: http-ws
      protocol: TCP
      port: 5678
      targetPort: 5678
    - name: grpc-http
      protocol: TCP
      port: 50051
      targetPort: 50051
  #type: LoadBalancer  # for tcp lb
  type: ClusterIP  # for ingress, gateway
  #type: NodePort  # gateway

---
apiVersion: v1
kind: Service
metadata:
  name: fla-service-f
  namespace: fla-na-c
  labels:
    app: fla-app-f  # required for group app
spec:
  selector:
    pod: fla-pod-f
    version: fla-v1
  ports:
    - name: http-web
      protocol: TCP  # "SCTP", "TCP", "UDP"
      port: 8080  # 8080 443
      targetPort: 8080
    - name: http-nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-proxy
      protocol: TCP
      port: 9191
      targetPort: 9191
    - name: http-proxy-tcp
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: http-udp
      protocol: UDP
      port: 5005
      targetPort: 5005
    - name: http-ws
      protocol: TCP
      port: 5678
      targetPort: 5678
    - name: grpc-http
      protocol: TCP
      port: 50051
      targetPort: 50051
  #type: LoadBalancer  # for tcp lb
  type: ClusterIP  # for ingress, gateway
  #type: NodePort  # gateway
