apiVersion: v1
kind: Service
metadata:
  name: fla-service-b
  namespace: fla-na-a
  labels:
    app: fla-app-b  # required for group app
  annotations:
  #  beta.cloud.google.com/backend-config: '{"ports": {"8080":"fla-backendconfig-a"}}'
  #  cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"my-port":"HTTP2"}'  # gcp: for grpc
    cloud.google.com/backend-config: '{"default": "fla-backendconfig-a"}'  # gcp: for readyness ingress timeout
spec:
  selector:
    pod: fla-pod-b
    version: fla-v1
  ports:
    - name: http-web
      protocol: TCP  # "SCTP", "TCP", "UDP"
      port: 8080  # 8080 443
      targetPort: 8080
    - name: http-nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-proxy
      protocol: TCP
      port: 9191
      targetPort: 9191
    - name: http-proxy-tcp
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: http-udp
      protocol: UDP
      port: 5005
      targetPort: 5005
    - name: http-ws
      protocol: TCP
      port: 5678
      targetPort: 5678
    - name: grpc-http
      protocol: TCP
      port: 50051
      targetPort: 50051
  #type: LoadBalancer  # for tcp lb
  type: ClusterIP  # for ingress, gateway
  #type: NodePort  # gateway
