apiVersion: v1
kind: Service
metadata:
  name: fla-service-z
  namespace: default-z
  labels:
    app: fla-app-z  # required for group app
spec:
  selector:
    pod: fla-pod-z
    version: fla-v1
  ports:
    - name: http-web
      protocol: TCP  # "SCTP", "TCP", "UDP"
      port: 8080  # 8080 443
      targetPort: 8080
    - name: http-nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-proxy
      protocol: TCP
      port: 9191
      targetPort: 9191
    - name: http-proxy-tcp
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: http-udp
      protocol: UDP
      port: 5005
      targetPort: 5005
    - name: http-ws
      protocol: TCP
      port: 5678
      targetPort: 5678
    - name: grpc-http
      protocol: TCP
      port: 50051
      targetPort: 50051
  #type: LoadBalancer  # for tcp lb
  type: ClusterIP  # for ingress, gateway
  #type: NodePort  # gateway
