apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default-a
spec:
  #type: ClusterIP
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080