apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-a-virtualservice
  namespace: default
spec:
  hosts:
  - '*'
  gateways:
  - flask-gateway
  http:
  - name: service-a-virtualservice
    route:
    - destination:
        host: service-a
        port:
          number: 80